// 🚀 File: components/documents/templates/layouts/VisaGuaranteeAdminLayout.jsx

import React from 'react';
import PropTypes from 'prop-types';
import VisaGuaranteeContent from '../VisaGuaranteeContent'; // 💡 Import เนื้อหา Visa

// Helper: Format วันที่ปัจจุบันสำหรับ Header
const formatCurrentDate = () => {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
};

/**
 * @component VisaGuaranteeAdminLayout
 * @description Layout Wrapper สำหรับ Visa Guarantee Letter (Standard International)
 */
const VisaGuaranteeAdminLayout = ({ data }) => {
  const currentDateFormatted = formatCurrentDate();

  // 💡 Note: Layout นี้ถูกออกแบบให้เน้นความเรียบง่ายและเป็นทางการตามมาตรฐานสากล
  // โดยไม่มีตราครุฑ แต่เน้นข้อมูลติดต่อของผู้รับรองใน Content Component

  return (
    // p-10 สำหรับระยะขอบที่กว้างขึ้นตามมาตรฐานเอกสารสากล
    <div className="min-h-[900px] p-10 font-sans text-gray-900">
      {/* 1. CONTENT AREA */}
      {/* ส่ง data และ currentDateFormatted ไปยัง Content */}
      <VisaGuaranteeContent data={data} currentDateFormatted={currentDateFormatted} />

      {/* 2. FOOTER (สามารถเพิ่มลายเซ็นต์กราฟิกที่นี่ได้ถ้ามี) */}
      {/* 💡 หากต้องการลายเซ็นต์กราฟิก สามารถเพิ่ม SignatureBlock ที่นี่ได้ */}
      {/* <SignatureBlock name={data.managerName} position={'Expert'} /> */}

      <div className="mt-10 border-t pt-2 text-center text-xs text-gray-500">
        This letter is generated by an expert consultant service and is solely for visa application
        purposes.
      </div>
    </div>
  );
};

VisaGuaranteeAdminLayout.propTypes = {
  data: PropTypes.object.isRequired,
};

export default VisaGuaranteeAdminLayout;
