#!/bin/bash

# ==============================================================================
# 🛠️ JP-VISOUL-DOCS: Project Structure Reporter (Structure Only)
# ==============================================================================
# Description: Generates a markdown report of project directory structure only.
# Features: Recursive directory mapping.
# ==============================================================================

# ⚙️ CONFIGURATION
OUTPUT_FILE="project-structure.md"

# Directories allowed for scanning (Strictly aligned with Next.js 15 App Router)
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "scripts"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
)

# Regex to ignore non-essential or sensitive files
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# 🚀 START EXECUTION
rm -f "$OUTPUT_FILE"

echo "🔍 Scanning JP-VISOUL-DOCS project architecture..."

{
  echo "# 📁 Project Structure Report: JP-VISOUL-DOCS"
  echo "> Generated on: **$(date '+%Y-%m-%d %H:%M:%S')**"
  echo ""

  # --- ARCHITECTURAL OVERVIEW ---
  echo "## 🌳 Directory Tree"
  echo "The following structure represents the core business logic and UI layers."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### 📂 $dir"

      find "$dir" -maxdepth 10 -not -path '*/.*' \
        | grep -vE "$IGNORE_PATTERN" \
        | while read -r path; do

          depth=$(temp="${path//[^\/]/}"; echo "${#temp}")
          indent=$(printf '%*s' $((depth * 2)) "")
          name=$(basename "$path")

          if [ -d "$path" ]; then
            [[ "$path" != "$dir" ]] && echo "${indent}📂 **$name/**"
          else
            echo "${indent}📄 $name"
          fi
        done

      echo ""
    fi
  done

  echo "---"
  echo "_Report generated by JP-VISOUL Internal Automation._"

} > "$OUTPUT_FILE"

echo "✅ Success: Report saved to → $OUTPUT_FILE"